# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
                ('contact_number', models.PositiveIntegerField()),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
    ]
