# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
