# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20171014_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='contact_number',
            field=models.CharField(max_length=20015),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email_address',
            field=models.EmailField(max_length=200),
        ),
    ]
